# Generated by Django 3.0.2 on 2020-02-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mlmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USERID_x', models.IntegerField()),
                ('DayDiff', models.FloatField()),
                ('DayDiff1', models.FloatField()),
                ('DayDiff2', models.FloatField()),
                ('DayDiffMean', models.FloatField()),
                ('DayDiffStd', models.FloatField()),
                ('NextPurchaseDayRange', models.FloatField()),
            ],
        ),
    ]
