# Generated by Django 3.0.2 on 2020-03-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_mlmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='mlmodel1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('date', models.IntegerField()),
                ('rqid', models.IntegerField()),
                ('pth', models.IntegerField()),
                ('values', models.IntegerField()),
            ],
        ),
    ]
